import type { TemplateField } from './types'

export const FIELD_LABELS: Record<TemplateField, string> = {
  title: 'Lesson Title',
  date: 'Date',
  grade: 'Grade / Class',
  subject: 'Subject',
  school: 'School',
  teacherName: 'Teacher Name',
  courseLevel: 'Course / Level',
  lessonTime: 'Lesson Time',
  location: 'Location / Facility',
  duration: 'Duration',
  outcomes: 'Curriculum Outcomes',
  objectives: 'Learning Goals',
  materials: 'Materials',
  resources: 'Resources',
  priorKnowledge: 'Prerequisites / Prior Knowledge',
  activities: 'Activities',
  assessment: 'Assessment',
  differentiation: 'Differentiation',
  extensions: 'Extensions',
  references: 'References',
  rubric: 'Rubric',
  safety: 'Safety Considerations',
  essentialQuestions: 'Essential Questions',
  essentialVocabulary: 'Essential Vocabulary',
  crossCurricular: 'Cross-Curricular Links',
  anticipatorySet: 'Anticipatory Set / Hook',
  bodySequence: 'Body / Strategies',
  closing: 'Closing / Consolidation',
  timedActivities: 'Timed Activity Table',
  understandingChecks: 'Check for Understanding',
  studentFeedback: 'Student Feedback',
  lookingAhead: 'Looking Ahead'
}

export const FIELD_HINTS: Partial<Record<TemplateField, string>> = {
  title: 'Write the official lesson or unit title.',
  date: 'Add calendar date for delivery.',
  grade: 'Specify the grade or class grouping.',
  subject: 'Identify the subject or pathway.',
  teacherName: 'Lead teacher or facilitator.',
  school: 'Site, school, or organization.',
  lessonTime: 'Block or timetable duration.',
  location: 'Room, lab, or digital context.',
  objectives: 'What should learners know or do by the end?',
  outcomes: 'List curriculum codes or outcome statements.',
  materials: 'List handouts, tech, or manipulatives.',
  resources: 'Include teacher and student-facing resources.',
  priorKnowledge: 'Note prerequisite concepts to activate.',
  assessment: 'Describe formative or summative evidence.',
  differentiation: 'Supports, extensions, or grouping moves.',
  extensions: 'Optional follow-up tasks or enrichment.',
  references: 'Cite sources, research, or media.',
  safety: 'Document hazards and mitigations.',
  essentialQuestions: 'Guiding questions that frame inquiry.',
  essentialVocabulary: 'Key terms to highlight.',
  crossCurricular: 'Connections to other subjects or competencies.',
  anticipatorySet: 'Hook, provocation, or entry event.',
  bodySequence: 'Detail the main instructional flow.',
  closing: 'Reflection, consolidation, or exit routines.',
  timedActivities: 'Break the lesson into timed blocks.',
  understandingChecks: 'Where will you verify understanding?',
  studentFeedback: 'Capture learner reflections or surveys.',
  lookingAhead: 'Preview upcoming lessons or homework.'
}

export const labelForField = (field: TemplateField) => FIELD_LABELS[field] || field
